import Link from "next/link";

export const metadata = {
  title: "showroom",
  description: "Generated by Next.js en una noche",
};

export default function ShowRoomLayout({ children }) {
  return (
    //importante solo colocar sections u otro tipo de etiqueta para poder anidar los layouts
    <section>
      <h1 style={{ background: "red" }}>este es el layout de showroom</h1>
      <nav style={{ background: "red" }}>
        <h1> este es el navbar de showroom</h1>
        <ul>
          <li>
            <Link href="/showroom/laptops">Laptops</Link>
          </li>
          <li>
            <Link href="/showroom">atras</Link>
          </li>
        </ul>
      </nav>

      {children}
    </section>
  );
}
